/*
 Generated by typeshare 1.0.0
*/

import { PermissionLevel, PermissionsTarget } from "../types";

export interface CreateBuildBody {
	name: string;
	server_id: string;
}

export interface CopyBuildBody {
	name: string;
	server_id: string;
}

export interface CreateDeploymentBody {
	name: string;
	server_id: string;
}

export interface CopyDeploymentBody {
	name: string;
	server_id: string;
}

export interface CreateGroupBody {
	name: string;
}

export interface LoginOptions {
	local: boolean;
	github: boolean;
	google: boolean;
}

export interface PermissionsUpdateBody {
	user_id: string;
	permission: PermissionLevel;
	target_type: PermissionsTarget;
	target_id: string;
}

export interface ModifyUserEnabledBody {
	user_id: string;
	enabled: boolean;
}

export interface CreateProcedureBody {
	name: string;
}

export interface CreateSecretBody {
	name: string;
	expires?: string;
}

export interface CreateServerBody {
	name: string;
	address: string;
}

export interface TokenExchangeBody {
	token: string;
}

