/*
 Generated by typeshare 1.0.0
*/

import { PermissionLevel, PermissionsTarget } from "../types";

export interface BuildId {
	id: string;
}

export interface CreateBuildBody {
	name: string;
	server_id: string;
}

export interface DeploymentId {
	id: string;
}

export interface CreateDeploymentBody {
	name: string;
	server_id: string;
}

export interface PermissionsUpdateBody {
	user_id: string;
	permission: PermissionLevel;
	target_type: PermissionsTarget;
	target_id: string;
}

export interface ModifyUserEnabledBody {
	user_id: string;
	enabled: boolean;
}

export interface CreateProcedureBody {
	name: string;
}

export interface CreateSecretBody {
	name: string;
	expires?: string;
}

export interface DeleteSecretPath {
	name: string;
}

export interface ServerId {
	id: string;
}

export interface CreateServerBody {
	name: string;
	address: string;
}

