/*
 Generated by typeshare 1.6.0
*/

export enum PermissionLevel {
	None = "none",
	Read = "read",
	Execute = "execute",
	Update = "update",
}

export type PermissionsMap = Record<string, PermissionLevel>;

export type I64 = number;

export type MongoDocument = any;

export type BuildBuilderConfig = 
	| { type: "Server", params: {
	server_id: string;
}}
	| { type: "Builder", params: {
	builder_id: string;
}};

export interface Version {
	major: number;
	minor: number;
	patch: number;
}

export interface SystemCommand {
	path?: string;
	command?: string;
}

export interface EnvironmentVar {
	variable: string;
	value: string;
}

export interface BuildConfig {
	builder: BuildBuilderConfig;
	skip_secret_interp?: boolean;
	version?: Version;
	repo?: string;
	branch: string;
	github_account?: string;
	docker_account?: string;
	docker_organization?: string;
	pre_build?: SystemCommand;
	build_path: string;
	dockerfile_path: string;
	build_args?: EnvironmentVar[];
	extra_args?: string[];
	use_buildx?: boolean;
	tags?: string[];
}

export interface Build {
	_id?: string;
	name: string;
	description?: string;
	permissions?: PermissionsMap;
	created_at?: I64;
	updated_at?: I64;
	last_built_at?: I64;
	config: BuildConfig;
}

export interface BuildActionState {
	building: boolean;
	updating: boolean;
}

export type BuilderConfig = 
	| { type: "AwsBuilder", params: AwsBuilder };

export interface Builder {
	_id?: string;
	name: string;
	description?: string;
	permissions?: PermissionsMap;
	created_at?: I64;
	updated_at?: I64;
	config: BuilderConfig;
}

export interface AwsBuilder {
	region: string;
	instance_type: string;
	volume_gb: number;
	ami_id: string;
	subnet_id: string;
	security_group_ids: string[];
	key_pair_name: string;
	assign_public_ip: boolean;
}

export enum TerminationSignal {
	SigHup = "SIGHUP",
	SigInt = "SIGINT",
	SigQuit = "SIGQUIT",
	SigTerm = "SIGTERM",
}

export interface TerminationSignalLabel {
	signal: TerminationSignal;
	label: string;
}

export interface Conversion {
	local: string;
	container: string;
}

export enum RestartMode {
	NoRestart = "no",
	OnFailure = "on-failure",
	Always = "always",
	UnlessStopped = "unless-stopped",
}

export interface DeploymentConfig {
	server_id?: string;
	build_id?: string;
	image?: string;
	skip_secret_interp?: boolean;
	redeploy_on_build?: boolean;
	term_signal_labels: TerminationSignalLabel[];
	termination_signal?: TerminationSignal;
	termination_timeout: number;
	ports?: Conversion[];
	volumes?: Conversion[];
	environment?: EnvironmentVar[];
	network: string;
	restart?: RestartMode;
	post_image?: string;
	container_user?: string;
	extra_args?: string[];
	docker_account?: string;
	tags?: string[];
}

export interface Deployment {
	_id?: string;
	name: string;
	description?: string;
	permissions?: PermissionsMap;
	created_at?: I64;
	updated_at?: I64;
	config: DeploymentConfig;
}

export enum DockerContainerState {
	Unknown = "Unknown",
	NotDeployed = "NotDeployed",
	Created = "Created",
	Restarting = "Restarting",
	Running = "Running",
	Removing = "Removing",
	Paused = "Paused",
	Exited = "Exited",
	Dead = "Dead",
}

export interface BasicContainerInfo {
	name: string;
	id: string;
	image: string;
	state: DockerContainerState;
	status?: string;
}

export interface DockerContainerStats {
	name: string;
	cpu_perc: string;
	mem_perc: string;
	mem_usage: string;
	net_io: string;
	block_io: string;
	pids: string;
}

export interface DeploymentActionState {
	deploying: boolean;
	stopping: boolean;
	starting: boolean;
	removing: boolean;
	pulling: boolean;
	recloning: boolean;
	updating: boolean;
	renaming: boolean;
}

export interface CloneArgs {
	name: string;
	repo?: string;
	branch?: string;
	on_clone?: SystemCommand;
	on_pull?: SystemCommand;
	github_account?: string;
}

export interface RepoConfig {
	repo: string;
	branch: string;
	github_account: string;
	on_clone: SystemCommand;
	on_pull: SystemCommand;
}

export interface Repo {
	_id?: string;
	name: string;
	description?: string;
	permissions?: PermissionsMap;
	created_at?: string;
	updated_at?: string;
	tags?: string[];
	config: RepoConfig;
}

export interface ImageSummary {
	/** ID is the content-addressable ID of an image.  This identifier is a content-addressable digest calculated from the image's configuration (which includes the digests of layers used by the image).  Note that this digest differs from the `RepoDigests` below, which holds digests of image manifests that reference the image. */
	Id: string;
	/** ID of the parent image.  Depending on how the image was created, this field may be empty and is only set for images that were built/created locally. This field is empty if the image was pulled from an image registry. */
	ParentId: string;
	/** List of image names/tags in the local image cache that reference this image.  Multiple image tags can refer to the same image, and this list may be empty if no tags reference the image, in which case the image is \"untagged\", in which case it can still be referenced by its ID. */
	RepoTags: string[];
	/** List of content-addressable digests of locally available image manifests that the image is referenced from. Multiple manifests can refer to the same image.  These digests are usually only available if the image was either pulled from a registry, or if the image was pushed to a registry, which is when the manifest is generated and its digest calculated. */
	RepoDigests: string[];
	/** Date and time at which the image was created as a Unix timestamp (number of seconds sinds EPOCH). */
	Created: I64;
	/** Total size of the image including all layers it is composed of. */
	Size: I64;
	/** Total size of image layers that are shared between this image and other images.  This size is not calculated by default. `-1` indicates that the value has not been set / calculated. */
	SharedSize: I64;
	/** Total size of the image including all layers it is composed of.  In versions of Docker before v1.10, this field was calculated from the image itself and all of its parent images. Docker v1.10 and up store images self-contained, and no longer use a parent-chain, making this field an equivalent of the Size field.  This field is kept for backward compatibility, but may be removed in a future version of the API. */
	VirtualSize: I64;
	/** User-defined key/value metadata. */
	Labels: Record<string, string>;
	/** Number of containers using this image. Includes both stopped and running containers.  This size is not calculated by default, and depends on which API endpoint is used. `-1` indicates that the value has not been set / calculated. */
	Containers: I64;
}

export interface IpamConfig {
	Subnet?: string;
	IPRange?: string;
	Gateway?: string;
	AuxiliaryAddresses?: Record<string, string>;
}

export interface Ipam {
	/** Name of the IPAM driver to use. */
	Driver?: string;
	/** List of IPAM configuration options, specified as a map:  ``` {\"Subnet\": <CIDR>, \"IPRange\": <CIDR>, \"Gateway\": <IP address>, \"AuxAddress\": <device_name:IP address>} ``` */
	Config?: IpamConfig[];
	/** Driver-specific options, specified as a map. */
	Options?: Record<string, string>;
}

export interface NetworkContainer {
	Name?: string;
	EndpointID?: string;
	MacAddress?: string;
	IPv4Address?: string;
	IPv6Address?: string;
}

export interface DockerNetwork {
	Name?: string;
	Id?: string;
	Created?: string;
	Scope?: string;
	Driver?: string;
	EnableIPv6?: boolean;
	IPAM?: Ipam;
	Internal?: boolean;
	Attachable?: boolean;
	Ingress?: boolean;
	Containers?: Record<string, NetworkContainer>;
	Options?: Record<string, string>;
	Labels?: Record<string, string>;
}

export interface ServerConfig {
	address: string;
	enabled: boolean;
	auto_prune: boolean;
	region?: string;
	cpu_warning: number;
	cpu_critical: number;
	mem_warning: number;
	mem_critical: number;
	disk_warning: number;
	disk_critical: number;
	to_notify?: string[];
	tags?: string[];
}

export interface Server {
	_id?: string;
	name: string;
	description?: string;
	permissions?: PermissionsMap;
	created_at?: I64;
	updated_at?: I64;
	config: ServerConfig;
}

export interface ServerActionState {
	pruning_networks: boolean;
	pruning_containers: boolean;
	pruning_images: boolean;
}

export interface SystemInformation {
	name?: string;
	os?: string;
	kernel?: string;
	core_count?: number;
	host_name?: string;
	cpu_brand: string;
}

export interface BasicSystemStats {
	system_load: number;
	cpu_perc: number;
	cpu_freq_mhz: number;
	mem_used_gb: number;
	mem_total_gb: number;
	disk_used_gb: number;
	disk_total_gb: number;
}

export interface SingleCpuUsage {
	name: string;
	usage: number;
}

export interface CpuUsage {
	cpu_perc: number;
	cpu_freq_mhz: number;
	cpus?: SingleCpuUsage[];
}

export interface SingleDiskUsage {
	mount: string;
	used_gb: number;
	total_gb: number;
}

export interface DiskUsage {
	used_gb: number;
	total_gb: number;
	read_kb: number;
	write_kb: number;
	disks?: SingleDiskUsage[];
}

export interface SystemNetwork {
	name: string;
	recieved_kb: number;
	transmitted_kb: number;
}

export interface NetworkUsage {
	recieved_kb: number;
	transmitted_kb: number;
	networks: SystemNetwork[];
}

export interface SystemProcess {
	pid: number;
	name: string;
	exe?: string;
	cmd: string[];
	start_time?: number;
	cpu_perc: number;
	mem_mb: number;
	disk_read_kb: number;
	disk_write_kb: number;
}

export interface SystemComponent {
	label: string;
	temp: number;
	max: number;
	critical?: number;
}

export enum Timelength {
	OneSecond = "1-sec",
	FiveSeconds = "5-sec",
	TenSeconds = "10-sec",
	FifteenSeconds = "15-sec",
	ThirtySeconds = "30-sec",
	OneMinute = "1-min",
	TwoMinutes = "2-min",
	FiveMinutes = "5-min",
	TenMinutes = "10-min",
	FifteenMinutes = "15-min",
	ThirtyMinutes = "30-min",
	OneHour = "1-hr",
	TwoHours = "2-hr",
	SixHours = "6-hr",
	EightHours = "8-hr",
	TwelveHours = "12-hr",
	OneDay = "1-day",
	ThreeDay = "3-day",
	OneWeek = "1-wk",
	TwoWeeks = "2-wk",
	ThirtyDays = "30-day",
}

export interface AllSystemStats {
	basic: BasicSystemStats;
	cpu: CpuUsage;
	disk: DiskUsage;
	network: NetworkUsage;
	processes?: SystemProcess[];
	components?: SystemComponent[];
	polling_rate: Timelength;
	refresh_ts: I64;
	refresh_list_ts: I64;
}

export enum StatsState {
	Ok = "Ok",
	Warning = "Warning",
	Critical = "Critical",
}

export interface ServerHealth {
	cpu: StatsState;
	mem: StatsState;
	disk: StatsState;
	disks: Record<string, StatsState>;
}

export type UpdateTarget = 
	| { type: "System", id?: undefined }
	| { type: "Build", id: string }
	| { type: "Builder", id: string }
	| { type: "Deployment", id: string }
	| { type: "Server", id: string };

export enum Operation {
	None = "None",
	CreateServer = "CreateServer",
	UpdateServer = "UpdateServer",
	DeleteServer = "DeleteServer",
	RenameServer = "RenameServer",
	PruneImagesServer = "PruneImagesServer",
	PruneContainersServer = "PruneContainersServer",
	PruneNetworksServer = "PruneNetworksServer",
	CreateBuild = "CreateBuild",
	UpdateBuild = "UpdateBuild",
	DeleteBuild = "DeleteBuild",
	RunBuild = "RunBuild",
	CreateDeployment = "CreateDeployment",
	UpdateDeployment = "UpdateDeployment",
	DeleteDeployment = "DeleteDeployment",
	DeployContainer = "DeployContainer",
	StopContainer = "StopContainer",
	StartContainer = "StartContainer",
	RemoveContainer = "RemoveContainer",
	PullDeployment = "PullDeployment",
	RecloneDeployment = "RecloneDeployment",
	RenameDeployment = "RenameDeployment",
	CreateProcedure = "CreateProcedure",
	UpdateProcedure = "UpdateProcedure",
	DeleteProcedure = "DeleteProcedure",
	CreateCommand = "CreateCommand",
	UpdateCommand = "UpdateCommand",
	DeleteCommand = "DeleteCommand",
	RunCommand = "RunCommand",
	CreateGroup = "CreateGroup",
	UpdateGroup = "UpdateGroup",
	DeleteGroup = "DeleteGroup",
	ModifyUserEnabled = "ModifyUserEnabled",
	ModifyUserCreateServerPermissions = "ModifyUserCreateServerPermissions",
	ModifyUserCreateBuildPermissions = "ModifyUserCreateBuildPermissions",
	ModifyUserPermissions = "ModifyUserPermissions",
	AutoBuild = "AutoBuild",
	AutoPull = "AutoPull",
}

export interface Log {
	stage: string;
	command: string;
	stdout: string;
	stderr: string;
	success: boolean;
	start_ts: I64;
	end_ts: I64;
}

export enum UpdateStatus {
	Queued = "Queued",
	InProgress = "InProgress",
	Complete = "Complete",
}

export interface Update {
	_id?: string;
	target: UpdateTarget;
	operation: Operation;
	logs: Log[];
	start_ts: I64;
	end_ts?: I64;
	status: UpdateStatus;
	success: boolean;
	operator: string;
	version: Version;
}

export interface ApiSecret {
	name: string;
	hash?: string;
	created_at: I64;
	expires?: I64;
}

export interface User {
	_id?: string;
	username: string;
	enabled?: boolean;
	admin?: boolean;
	create_server_permissions?: boolean;
	create_build_permissions?: boolean;
	avatar?: string;
	secrets?: ApiSecret[];
	password?: string;
	github_id?: string;
	google_id?: string;
	created_at?: I64;
	updated_at?: I64;
}

export interface RunBuild {
	build_id: string;
}

export interface RenameDeployment {
	id: string;
	name: string;
}

export interface Deploy {
	deployment_id: string;
}

export interface StartContainer {
	deployment_id: string;
}

export interface StopContainer {
	deployment_id: string;
	signal?: TerminationSignal;
	time?: number;
}

export interface RemoveContainer {
	deployment_id: string;
	signal?: TerminationSignal;
	time?: number;
}

export interface CreateLoginSecret {
	name: string;
	expires?: I64;
}

export interface CreateLoginSecretResponse {
	secret: string;
}

export interface DeleteLoginSecret {
	name: string;
}

export interface RenameServer {
	id: string;
	name: string;
}

export interface GetPeripheryVersion {
	server_id: string;
}

export interface GetPeripheryVersionResponse {
	version: string;
}

export interface GetAllSystemStats {
	server_id: string;
}

export interface GetLoginOptions {
}

export interface GetLoginOptionsResponse {
	local: boolean;
	github: boolean;
	google: boolean;
}

export interface CreateLocalUser {
	username: string;
	password: string;
}

export interface CreateLocalUserResponse {
	jwt: string;
}

export interface LoginLocalUser {
	username: string;
	password: string;
}

export interface LoginLocalUserResponse {
	jwt: string;
}

export interface ExchangeForJwt {
	token: string;
}

export interface ExchangeForJwtResponse {
	jwt: string;
}

export interface LoginWithSecret {
	username: string;
	secret: string;
}

export interface LoginWithSecretResponse {
	jwt: string;
}

export enum ServerStatus {
	NotOk = "NotOk",
	Ok = "Ok",
	Disabled = "Disabled",
}

