FROM rust:latest as builder
WORKDIR /core

COPY ./lib/db_client .
COPY ./lib/helpers .
COPY ./lib/periphery_client .
COPY ./lib/types .
COPY ./core .

RUN cargo build -p core --release

FROM gcr.io/distroless/cc
COPY --from=builder /core/target/release/core /

CMD ["./core"]