FROM rust:latest as builder
WORKDIR /builder

COPY ./periphery ./periphery

COPY ./lib/types ./lib/types
COPY ./lib/helpers ./lib/helpers

RUN cd periphery && cargo build --release

FROM debian:stable-slim

ARG DEPS_INSTALLER

COPY ./${DEPS_INSTALLER}.sh ./
RUN sh ./${DEPS_INSTALLER}.sh

COPY --from=builder /builder/periphery/target/release/periphery /usr/local/bin/periphery

EXPOSE 8000

CMD "periphery"