/* BUILD */
export const CREATE_BUILD = "CREATE_BUILD";
export const DELETE_BUILD = "DELETE_BUILD";
export const UPDATE_BUILD = "UPDATE_BUILD";
export const BUILD = "BUILD";
export const CLONE_BUILD_REPO = "CLONE_BUILD_REPO";
export const PULL_BUILD = "PULL_BUILD";
export const BUILD_OWNER_UPDATE = "BUILD_OWNER_UPDATE";

/* DEPLOY */
export const CREATE_DEPLOYMENT = "CREATE_DEPLOYMENT";
export const DELETE_DEPLOYMENT = "DELETE_DEPLOYMENT";
export const UPDATE_DEPLOYMENT = "UPDATE_DEPLOYMENT";
export const DEPLOY = "DEPLOY";
export const START_CONTAINER = "START_CONTAINER";
export const STOP_CONTAINER = "STOP_CONTAINER";
export const DELETE_CONTAINER = "DELETE_CONTAINER";
export const REFRESH_CONTAINER_STATUS = "REFRESH_CONTAINER_STATUS";
export const COPY_ENV = "COPY_ENV";
export const CLONE_DEPLOYMENT_REPO = "CLONE_DEPLOYMENT_REPO";
export const PULL_DEPLOYMENT = "PULL_DEPLOYMENT";
export const DEPLOYMENT_OWNER_UPDATE = "DEPLOYMENT_OWNER_UPDATE";
export const RECLONE_DEPLOYMENT_REPO = "RECLONE_DEPLOYMENT_REPO";

/* SERVER */
export const ADD_SERVER = "ADD_SERVER";
export const REMOVE_SERVER = "REMOVE_SERVER";
export const UPDATE_SERVER = "UPDATE_SERVER";
export const PRUNE_IMAGES = "PRUNE_IMAGES";
export const PRUNE_CONTAINERS = "PRUNE_CONTAINERS";
export const GET_SERVER_STATS = "GET_SERVER_STATS";
export const CREATE_NETWORK = "CREATE_NETWORK";
export const DELETE_NETWORK = "DELETE_NETWORK";
export const PRUNE_NETWORKS = "PRUNE_NETWORKS";
export const SERVER_OWNER_UPDATE = "SERVER_OWNER_UPDATE";

/* UPDATE */
export const ADD_UPDATE = "ADD_UPDATE";

/* ALERT */
export const ALERT = "ALERT";

/* USERS */
export const USER_UPDATE = "USER_UPDATE";
